version: '3'
services:
    redis:
        image: redis:alpine
        networks:
            - frontend
        deploy:
          replicas: 3
    db:
        image: postgres:9.6
        volumes:
            - db-data:/var/lib/postgresql/data
        environment:
            - POSTGRES_HOST_AUTH_METHOD=trust
        networks:
            - backend
        deploy:
          replicas: 2
          placement:
            constraints: [node.role == manager]    
    vote:
        image: bretfisher/examplevotingapp_vote
        ports:
            - '5000:80'
        networks:
            - frontend
        deploy:
          replicas: 6
          placement:
            constraints: [node.role == worker]
    result:
        image: bretfisher/examplevotingapp_result
        ports:
            - '5001:80'
        networks:
            - backend
    worker:
        image: bretfisher/examplevotingapp_worker:java
        networks:
            - frontend
            - backend
        deploy:
          mode: global
          replicas: 10
          placement:
            constraints: [node.role == worker]
    visualizer_service:
        image: dockersamples/visualizer
        ports: "8080:8080"
        stop_grace_period: 1m30s
        volumes:
            - "/var/run/docker.sock:/var/run/docker.sock"
        deploy:
          placement:
          constraints: [node.role == manager]
networks:
    frontend: null
    backend: null
volumes:
    db-data: null